on:
  - pull_request
  - push

name: build

jobs:
  Ci_simple:
    runs-on: ubuntu-latest
          
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies with composer php PHP [5.6 - 8.0]
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: ☁ base de datos
        run: |
          mysql --version
          sudo service mysql start

      - name: Setup Runner Database
        run: |
          mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS portal_mandatos;'
          mysql -uroot -h127.0.0.1 -proot portal_mandatos < etc/databases/portal_mandatos.sql;
          mysql -uroot -h127.0.0.1 -proot -e 'SHOW DATABASES;'
      
      - name: 👿 Wait for the environment to get up
        run: |
          while ! mysql -uroot -h127.0.0.1 -proot -Dportal_mandatos -e 'SELECT COUNT(*) FROM user;' --silent &> /dev/null ; do
              echo "Waiting for database connection..."
              sleep 2
          done

      - name: Run tests with codeception
        run: |
          vendor/bin/codecept run
        shell: bash
